name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - uses: actions/setup-node@v3
      with:
        node-version: "20"
        
    - name: Update npm and install dependencies
      run: |
        npm install -g npm@latest
        rm -rf node_modules package-lock.json
        npm cache clean --force
        
    - name: Install Rollup manually and dependencies
      run: |
        npm install @rollup/rollup-linux-x64-gnu --save-dev --no-optional
        npm install rollup@4.21.2 --save-dev
        npm install --legacy-peer-deps --force
        
    - name: Build project
      run: npm run build
      env:
        CI: false
        NODE_ENV: production
        NODE_OPTIONS: "--max-old-space-size=8192"
        ROLLUP_NO_NATIVE: "true"
        
    - name: Deploy to GitHub Pages
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        npm run deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
